// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class some_fixes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
